name: CDelivery
on:
  push:
    branches:
      - 'dev'
      - 'uat'
      - 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: JayNg96/ReleasesFlow    
          
      - name: Install Libraries
        run: |
          pip install flake8 pytest pytest-cov pandas Flask Flask-MySQLdb Flask-SQLAlchemy mysql-connector-python-rf PyMySQL SQLAlchemy   

      - name: list out contents
        run: |
          ls
          
      - name: test with pytest
        run: |
          python -m pytest tests/test_* -v -cov
    
        
  create-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    needs: build
    environment: PROD
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: JayNg96/ReleasesFlow
        
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json,./package-lock.json"
        
      - name: create release
        id: create-new-release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ steps.changelog.outputs.tag }}.zip
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./${{ steps.changelog.outputs.tag }}.zip
          asset_name: ${{ steps.changelog.outputs.tag }}.zip
          asset_content_type: application/zip
          
      - name: Create release branch
        run: |
          git branch release/${{ steps.changelog.outputs.tag }}
          git push -u origin release/${{ steps.changelog.outputs.tag }}
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.changelog.outputs.tag }}
          title: "Release ${{ steps.changelog.outputs.tag }}"
          body: "This pull request is to deploy the code from UAT to the release branch"
          labels: "deployment"
          reviewers: "JayNg96"
        
